# Generated by Django 4.2.5 on 2023-09-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotiontrack',
            name='time',
            field=models.TimeField(),
        ),
    ]
